### ISSUE TITLE
Cannot catch ImagePullError?

### ISSUE THREAD

**Issue by vreuter** [tweag/funflow2#102]
Working in a notebook, when I used `tryE` with a `Flow DockerTaskInput -> IO String`, designed to trigger an `ImagePullError`, I noticed I could not catch it while declaring `@DockerClientError`, and in fact I can't catch it even if I declare `@SomeException`. It seems like the implementation of `runFlowWithConfig` prevents the `ImagePullError` from being handled through `tryE`? Is that so, and is it intentional?

https://github.com/tweag/funflow2/blob/642cbb6a1eb3c03b31fe32d22886e4eba4b877cc/funflow/src/Funflow/Run.hs#L177-L183

**Comment by dorranh** [comment]
Hey @vreuter, this is indeed intended behavior. Looking up the type signature for tryE (in the kernmantle source) shows the following: 

```haskell
-- | A class for binary effects that can catch exceptions
class TryEffect ex eff where
  tryE :: eff a b -> eff a (Either ex b)
```

This means that the `tryE` is for transforming a binary effect (in our case a `Flow`) into one which can catch exceptions. This happens when the pipeline is actually executed (`performP`). 

In contrast, the section of `runFlowWithConfig` in question is one level of abstraction above the Flow where the Flow itself is being unwrapped, configured, and executed. `runFlowWithConfig` returns an `IO output`, so all of the stuff we are doing in this function is actually happening inside the IO monad. 

You should still be able to catch an exception when calling `runFlowWithConfig` with something like https://hackage.haskell.org/package/base-4.15.0.0/docs/Control-Exception.html#g:3

**Comment by vreuter** [comment]
Great, totally makes sense, thanks for confirming and elaborating.
