### ISSUE TITLE
Source of import of Cayley alias

### ISSUE THREAD

**Issue by vreuter** [tweag/funflow2#118]
`~>` is imported as the alias for `Cayley` from the re-export in `Control.Kernmantle.Rope`, rather than directly from the declaration in `Data.Profunctor.Trans`. This has tripped me up a couple of times remembering where it's defined. At least per `kernmantle.cabal`, the module in which the alias is declared is exported. What's the reason to import from `Kernmantle.Rope` rather than directly from `Profunctor.Trans`?

**Comment by dorranh** [comment]
Hi @vreuter, that's a good point. I think the reason for this is a mix of convenience (you can import everything you need to work with a Rope from `Control.Kernmantle.Rope`) and also abstraction since technically kernmantle could use other implementations of `~>` than the one defined in `Data.Profunctor.Trans` (e.g. if an abstraction other than Arrows were used for kernmantle's implementation). In practice this probably won't ever be the case, but it is a bit cleaner to make your pipelines depend only on `Control.Kernmantle.Rope`.

**Comment by vreuter** [comment]
I see what you mean. I was thinking of `Data.Profunctor.Trans` _as_ "part of" kernmantle, rather than considering the full modularity. This makes sense now, beyond even the convenience of the single source of import as you note.
