### ISSUE TITLE
API docs for DockerTask

### ISSUE THREAD

**Issue by vreuter** [tweag/funflow2#97]
In the "Error Handling" tutorial, there's a note:
> More about that in the API documentation of the Docker task.

where "that" is about possible docker task error modes. I don't see anything about those in the API docs for `DockerTask`, though. Am I missing something, or should we either:
- [x] remove the note from the tutorial
- ~~[ ] add to the task API docs~~

![Screenshot from 2021-05-26 15-11-49](https://user-images.githubusercontent.com/12036370/119724232-767ab300-be3c-11eb-8bbb-fcbb04a87727.png)

**Comment by vreuter** [comment]
Similar to #99 , @dorranh I can change based on what you think's best, just assigned you for now to weigh on best course.

**Comment by dorranh** [comment]
Good catch, @vreuter. I think we can just remove this comment since the possible types of errors a flow can throw depend on whether or not the user is using the default run function or an extended flow (the required types are here in `RequiredCore` by the way: https://tweag.github.io/funflow2/api/funflow/html/Funflow-Flow.html)
